# Generated by Django 3.2.2 on 2021-05-23 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_number', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='航班号')),
                ('origination', models.CharField(max_length=32, verbose_name='始发地')),
                ('destination', models.CharField(max_length=32, verbose_name='目的地')),
                ('departure_airport', models.CharField(max_length=64, verbose_name='始发机场')),
                ('landing_airport', models.CharField(max_length=64, verbose_name='目的机场')),
                ('starting_time', models.TimeField(verbose_name='始发时间')),
                ('flight_time', models.TimeField(blank=True, verbose_name='飞行时间')),
                ('arrival_time', models.TimeField(verbose_name='到达时间')),
                ('first_class_price', models.FloatField(default=2000, verbose_name='头等舱价格')),
                ('highlevel_economy_class_price', models.FloatField(default=1500, verbose_name='经济舱价格')),
                ('business_class_price', models.FloatField(default=1000, verbose_name='商务舱价格')),
                ('economy_class_price', models.FloatField(default=500, verbose_name='经济舱价格')),
                ('book_sum', models.IntegerField(default=0, verbose_name='订票总数')),
                ('plane_type', models.CharField(choices=[('波音', (('1', '747'), ('2', '767'), ('3', '777'))), ('空客', (('4', 'A300'), ('5', 'A310'), ('6', 'A320'), ('7', 'A340')))], max_length=30, verbose_name='飞机型号')),
                ('plane_capacity', models.IntegerField(blank=True, verbose_name='飞机容量')),
            ],
            options={
                'verbose_name': '航班信息',
                'verbose_name_plural': '航班信息',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.AutoField(primary_key=True, serialize=False, verbose_name='订单编号')),
                ('price', models.FloatField(verbose_name='机票价格')),
                ('order_time', models.DateTimeField(auto_now_add=True, verbose_name='订单创建时间')),
                ('seat_number', models.IntegerField(verbose_name='座位号')),
                ('order_is_valid', models.BooleanField(default=True, verbose_name='订单是否有效')),
                ('luggage_weight', models.FloatField(default=0, verbose_name='行李重量')),
                ('flight_type', models.CharField(choices=[('2', '高端经济舱'), ('4', '经济舱'), ('3', '商务舱'), ('1', '头等舱')], max_length=1, verbose_name='舱位类型')),
                ('flight', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='background.flight', verbose_name='航班')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='login.user', verbose_name='用户')),
            ],
        ),
    ]
