# Generated by Django 3.2.2 on 2021-05-24 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210524_1900'),
        ('background', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='plane_type',
            field=models.CharField(choices=[('波音', (('1', '747'), ('2', '777'), ('3', '787'))), ('空客', (('4', 'A300'), ('5', 'A310'), ('6', 'A320'), ('7', 'A350')))], max_length=30, verbose_name='飞机型号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='background.flight', verbose_name='航班'),
        ),
        migrations.AlterField(
            model_name='order',
            name='flight_type',
            field=models.CharField(choices=[('2', '高端经济舱'), ('3', '商务舱'), ('1', '头等舱'), ('4', '经济舱')], max_length=1, verbose_name='舱位类型'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user', verbose_name='用户'),
        ),
        migrations.CreateModel(
            name='Concrete_flight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_sum', models.IntegerField(default=0, verbose_name='订票总数')),
                ('plane_capacity', models.IntegerField(blank=True, verbose_name='飞机容量')),
                ('flight_datetime', models.DateTimeField(verbose_name='航班时间')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='background.flight', verbose_name='航班')),
            ],
        ),
    ]
