# Generated by Django 3.2.2 on 2021-05-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0002_auto_20210524_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concrete_flight',
            old_name='flight',
            new_name='flight_number',
        ),
        migrations.RenameField(
            model_name='concrete_flight',
            old_name='id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='flight',
            new_name='flight_number',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='flight_type',
            field=models.CharField(choices=[('3', '商务舱'), ('4', '经济舱'), ('2', '高端经济舱'), ('1', '头等舱')], max_length=1, verbose_name='舱位类型'),
        ),
    ]
