# Generated by Django 3.2.2 on 2021-05-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0003_auto_20210525_0907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concrete_flight',
            old_name='flight_number',
            new_name='flight',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='flight_number',
            new_name='flight',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='flight_type',
            field=models.CharField(choices=[('2', '高端经济舱'), ('4', '经济舱'), ('3', '商务舱'), ('1', '头等舱')], max_length=1, verbose_name='舱位类型'),
        ),
    ]
