# Generated by Django 3.2.2 on 2021-05-26 08:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0004_auto_20210525_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concrete_flight',
            old_name='user_id',
            new_name='id',
        ),
        migrations.AddField(
            model_name='order',
            name='flight_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 8, 24, 5, 504545), verbose_name='航班飞行具体时间'),
        ),
        migrations.CreateModel(
            name='FlightSeatingChart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_number', models.IntegerField(verbose_name='座位号')),
                ('is_occupied', models.BooleanField(default=False, verbose_name='该座位是否被占用')),
                ('concrete_flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='background.concrete_flight', verbose_name='具体航班')),
            ],
        ),
    ]
