# Generated by Django 3.2.2 on 2021-05-26 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0005_auto_20210526_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='flight_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 8, 46, 9, 444260), verbose_name='航班飞行具体时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='flight_type',
            field=models.CharField(choices=[('2', '高端经济舱'), ('3', '商务舱'), ('1', '头等舱'), ('4', '经济舱')], max_length=1, verbose_name='舱位类型'),
        ),
    ]
