# Generated by Django 3.2.2 on 2021-06-03 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0007_auto_20210531_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='flight_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 3, 16, 51, 48, 908580), verbose_name='航班飞行具体时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='flight_type',
            field=models.CharField(choices=[('2', '高端经济舱'), ('4', '经济舱'), ('1', '头等舱'), ('3', '商务舱')], max_length=1, verbose_name='舱位类型'),
        ),
    ]
