# Generated by Django 3.2.2 on 2021-05-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0008_auto_20210519_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_is_valid',
            field=models.BooleanField(default=True, verbose_name='订单是否有效'),
        ),
        migrations.AlterField(
            model_name='order',
            name='flight_type',
            field=models.CharField(choices=[('2', '高端经济舱'), ('1', '头等舱'), ('3', '商务舱'), ('4', '经济舱')], max_length=1, verbose_name='舱位类型'),
        ),
    ]
