# Generated by Django 3.2.2 on 2021-05-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0009_auto_20210519_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='航班号'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_time',
            field=models.TimeField(blank=True, verbose_name='飞行时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='flight_type',
            field=models.CharField(choices=[('4', '经济舱'), ('3', '商务舱'), ('2', '高端经济舱'), ('1', '头等舱')], max_length=1, verbose_name='舱位类型'),
        ),
    ]
