# Generated by Django 3.2.2 on 2021-05-23 19:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='用户名')),
                ('real_name', models.CharField(blank=True, max_length=128, verbose_name='真实姓名')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32, verbose_name='邮箱')),
                ('register_time', models.DateTimeField(auto_now_add=True)),
                ('last_login_time', models.DateTimeField(auto_now=True, verbose_name='上次登录时间')),
                ('birthday', models.DateField(blank=True, default=datetime.date(2021, 5, 23), verbose_name='生日')),
                ('phone_number', models.CharField(max_length=32, unique=True, verbose_name='手机号码')),
                ('Id_number', models.CharField(max_length=32, unique=True, verbose_name='身份证号')),
                ('credit_rating', models.CharField(choices=[('1', 'C'), ('2', 'B'), ('4', 'AA'), ('5', 'AAA'), ('3', 'A')], default='3', max_length=10, verbose_name='信用等级')),
                ('has_confirmed', models.BooleanField(default=False, verbose_name='是否已经邮箱验证')),
                ('flight_mileage', models.FloatField(default=0, verbose_name='飞行里程')),
                ('total_consumption', models.FloatField(default=0, verbose_name='消费总额')),
                ('balance', models.FloatField(default=0, verbose_name='余额')),
                ('profession', models.CharField(blank=True, max_length=32, verbose_name='职业')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-register_time'],
            },
        ),
        migrations.CreateModel(
            name='ConfirmString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.user')),
            ],
            options={
                'verbose_name': '确认码',
                'verbose_name_plural': '确认码',
                'ordering': ['-c_time'],
            },
        ),
    ]
