# Generated by Django 3.2.2 on 2021-05-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20210525_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credit_rating',
            field=models.CharField(choices=[('4', 'AA'), ('5', 'AAA'), ('3', 'A'), ('1', 'C'), ('2', 'B')], default='3', max_length=10, verbose_name='信用等级'),
        ),
    ]
