# Generated by Django 3.2.2 on 2021-05-26 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_user_credit_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.date(2021, 5, 26), verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='credit_rating',
            field=models.CharField(choices=[('2', 'B'), ('3', 'A'), ('1', 'C'), ('4', 'AA'), ('5', 'AAA')], default='3', max_length=10, verbose_name='信用等级'),
        ),
    ]
