# Generated by Django 3.2.2 on 2021-05-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20210526_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credit_rating',
            field=models.CharField(choices=[('1', 'C'), ('3', 'A'), ('2', 'B'), ('4', 'AA'), ('5', 'AAA')], default='3', max_length=10, verbose_name='信用等级'),
        ),
    ]
