# Generated by Django 3.2.2 on 2021-06-03 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20210531_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_super',
            field=models.BooleanField(default=False, verbose_name='是否是管理员'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.date(2021, 6, 3), verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='credit_rating',
            field=models.CharField(choices=[('5', 'AAA'), ('1', 'C'), ('3', 'A'), ('4', 'AA'), ('2', 'B')], default='3', max_length=10, verbose_name='信用等级'),
        ),
    ]
