# Generated by Django 3.2.2 on 2021-06-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20210603_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credit_rating',
            field=models.CharField(choices=[('3', 'A'), ('2', 'B'), ('5', 'AAA'), ('4', 'AA'), ('1', 'C')], default='3', max_length=10, verbose_name='信用等级'),
        ),
    ]
