# Generated by Django 3.2.2 on 2021-05-18 23:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210513_1454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-register_time'], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='c_time',
            new_name='register_time',
        ),
        migrations.AddField(
            model_name='user',
            name='Id_number',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='身份证号'),
        ),
        migrations.AddField(
            model_name='user',
            name='credit_rating',
            field=models.CharField(choices=[('2', 'B'), ('1', 'C'), ('4', 'AA'), ('5', 'AAA'), ('3', 'A')], default='B', max_length=10, verbose_name='信用等级'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 18, 23, 31, 38, 132680), verbose_name='上次登录时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_confirmed',
            field=models.BooleanField(default=False, verbose_name='是否已经邮箱验证'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=256, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32, verbose_name='邮箱'),
        ),
    ]
