# Generated by Django 3.2.2 on 2021-05-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20210518_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credit_rating',
            field=models.CharField(choices=[('5', 'AAA'), ('4', 'AA'), ('1', 'C'), ('2', 'B'), ('3', 'A')], default='B', max_length=10, verbose_name='信用等级'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login_time',
            field=models.DateTimeField(auto_now=True, verbose_name='上次登录时间'),
        ),
    ]
