# Generated by Django 3.2.2 on 2021-05-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20210519_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Id_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='credit_rating',
            field=models.CharField(choices=[('3', 'A'), ('1', 'C'), ('4', 'AA'), ('5', 'AAA'), ('2', 'B')], default='B', max_length=10, verbose_name='信用等级'),
        ),
    ]
