# Generated by Django 3.2.2 on 2021-05-19 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20210519_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 5, 19, 15, 55, 15, 801023), verbose_name='生日'),
        ),
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(blank=True, max_length=32, verbose_name='职业'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Id_number',
            field=models.CharField(max_length=32, unique=True, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='credit_rating',
            field=models.CharField(choices=[('4', 'AA'), ('1', 'C'), ('5', 'AAA'), ('3', 'A'), ('2', 'B')], default='3', max_length=10, verbose_name='信用等级'),
        ),
    ]
