# Generated by Django 3.2.2 on 2021-05-19 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.date(2021, 5, 19), verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='credit_rating',
            field=models.CharField(choices=[('3', 'A'), ('5', 'AAA'), ('2', 'B'), ('1', 'C'), ('4', 'AA')], default='3', max_length=10, verbose_name='信用等级'),
        ),
    ]
