# Generated by Django 3.2.2 on 2021-05-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20210519_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credit_rating',
            field=models.CharField(choices=[('1', 'C'), ('2', 'B'), ('4', 'AA'), ('3', 'A'), ('5', 'AAA')], default='3', max_length=10, verbose_name='信用等级'),
        ),
    ]
