# Generated by Django 3.2.2 on 2021-05-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20210520_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.FloatField(default=0, verbose_name='余额'),
        ),
        migrations.AlterField(
            model_name='user',
            name='credit_rating',
            field=models.CharField(choices=[('5', 'AAA'), ('1', 'C'), ('4', 'AA'), ('3', 'A'), ('2', 'B')], default='3', max_length=10, verbose_name='信用等级'),
        ),
    ]
