# Generated by Django 3.2.2 on 2021-05-23 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20210522_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.date(2021, 5, 23), verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='credit_rating',
            field=models.CharField(choices=[('1', 'C'), ('4', 'AA'), ('5', 'AAA'), ('3', 'A'), ('2', 'B')], default='3', max_length=10, verbose_name='信用等级'),
        ),
    ]
