# Generated by Django 3.2.2 on 2021-05-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20210523_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credit_rating',
            field=models.CharField(choices=[('4', 'AA'), ('2', 'B'), ('3', 'A'), ('5', 'AAA'), ('1', 'C')], default='3', max_length=10, verbose_name='信用等级'),
        ),
    ]
