# Generated by Django 3.2.2 on 2021-05-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_alter_user_credit_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credit_rating',
            field=models.CharField(choices=[('4', 'AA'), ('1', 'C'), ('3', 'A'), ('2', 'B'), ('5', 'AAA')], default='3', max_length=10, verbose_name='信用等级'),
        ),
    ]
