# Generated by Django 3.2.2 on 2021-05-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_number', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='航班号')),
                ('flight_type', models.CharField(choices=[('4', '经济舱'), ('1', '头等舱'), ('2', '高端经济舱'), ('3', '商务舱')], default='经济舱', max_length=1, verbose_name='航班类型')),
                ('origination', models.CharField(max_length=30, verbose_name='始发地')),
                ('destination', models.CharField(max_length=30, verbose_name='目的地')),
                ('starting_time', models.TimeField(verbose_name='始发时间')),
                ('flight_time', models.CharField(max_length=20, verbose_name='飞行时间')),
                ('arrival_time', models.TimeField(verbose_name='到达时间')),
                ('flight_price', models.FloatField(verbose_name='航班价格')),
            ],
        ),
    ]
