# Generated by Django 3.2.2 on 2021-05-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0003_auto_20210517_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='plane_capacity',
            field=models.IntegerField(blank=True, default=100, verbose_name='飞机容量'),
        ),
        migrations.AddField(
            model_name='flight',
            name='plane_type',
            field=models.CharField(default=100, max_length=30, unique=True, verbose_name='飞机型号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_type',
            field=models.CharField(choices=[('1', '头等舱'), ('4', '经济舱'), ('2', '高端经济舱'), ('3', '商务舱')], default='经济舱', max_length=1, verbose_name='航班类型'),
        ),
    ]
