# Generated by Django 3.2.2 on 2021-05-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0006_auto_20210518_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_type',
            field=models.CharField(choices=[('4', '经济舱'), ('3', '商务舱'), ('1', '头等舱'), ('2', '高端经济舱')], default='经济舱', max_length=1, verbose_name='航班类型'),
        ),
    ]
