# Generated by Django 3.2.2 on 2021-05-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0010_auto_20210519_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='flight_type',
            field=models.CharField(choices=[('3', '商务舱'), ('2', '高端经济舱'), ('4', '经济舱'), ('1', '头等舱')], max_length=1, verbose_name='舱位类型'),
        ),
    ]
