# Generated by Django 3.2.2 on 2021-05-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0012_alter_order_flight_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='departure_airport',
            field=models.CharField( max_length=32, verbose_name='始发机场'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='landing_airport',
            field=models.CharField(max_length=32, verbose_name='目的机场'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(max_length=32, verbose_name='目的地'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='origination',
            field=models.CharField(max_length=32, verbose_name='始发地'),
        ),
        migrations.AlterField(
            model_name='order',
            name='flight_type',
            field=models.CharField(choices=[('3', '商务舱'), ('4', '经济舱'), ('2', '高端经济舱'), ('1', '头等舱')], max_length=10, verbose_name='舱位类型'),
        ),
    ]
