# Generated by Django 3.2.2 on 2021-05-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0013_auto_20210519_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='flight_type',
            field=models.CharField(choices=[('4', '经济舱'), ('1', '头等舱'), ('2', '高端经济舱'), ('3', '商务舱')], max_length=1, verbose_name='舱位类型'),
        ),
    ]
