# Generated by Django 3.2.2 on 2021-05-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0014_alter_order_flight_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='luggage_weight',
            field=models.FloatField(default=0, verbose_name='行李重量'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_airport',
            field=models.CharField(max_length=64, verbose_name='始发机场'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='landing_airport',
            field=models.CharField(max_length=64, verbose_name='目的机场'),
        ),
        migrations.AlterField(
            model_name='order',
            name='flight_type',
            field=models.CharField(choices=[('2', '高端经济舱'), ('1', '头等舱'), ('3', '商务舱'), ('4', '经济舱')], max_length=1, verbose_name='舱位类型'),
        ),
    ]
