# Generated by Django 3.2.2 on 2021-05-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0015_auto_20210520_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='flight_type',
            field=models.CharField(choices=[('2', '高端经济舱'), ('4', '经济舱'), ('3', '商务舱'), ('1', '头等舱')], max_length=1, verbose_name='舱位类型'),
        ),
    ]
