# Generated by Django 3.2.2 on 2021-05-23 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20210523_1921'),
        ('background', '0017_alter_order_flight_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'verbose_name': '航班信息', 'verbose_name_plural': '航班信息'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='Id_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='flight_number',
        ),
        migrations.AddField(
            model_name='order',
            name='flight',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='background.flight', verbose_name='航班'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='login.user', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='order',
            name='flight_type',
            field=models.CharField(choices=[('2', '高端经济舱'), ('4', '经济舱'), ('3', '商务舱'), ('1', '头等舱')], max_length=1, verbose_name='舱位类型'),
        ),
    ]
